# Generated by Django 5.0.6 on 2024-09-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100)),
                ('name2', models.CharField(max_length=100)),
                ('relationship_start_date', models.DateField()),
                ('relationship_start_time', models.TimeField()),
                ('message', models.TextField()),
                ('youtube_link', models.URLField()),
                ('photos', models.ImageField(blank=True, null=True, upload_to='relationship_photos/')),
            ],
        ),
    ]
