# Generated by Django 5.0.6 on 2024-09-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteDeclaracao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='arquivos',
            field=models.FileField(blank=True, null=True, upload_to='relationship_files/'),
        ),
    ]
