# Generated by Django 5.0.6 on 2024-09-16 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteDeclaracao', '0002_relationship_arquivos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='media/relationship_files/')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='siteDeclaracao.relationship')),
            ],
        ),
    ]
