# Generated by Django 5.0.6 on 2024-09-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteDeclaracao', '0003_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='relationship_files/'),
        ),
    ]
