# Generated by Django 5.0.6 on 2024-09-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteDeclaracao', '0004_alter_fotos_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotos',
            name='name',
            field=models.CharField(default='Fotos', max_length=100),
        ),
    ]
