# Generated by Django 5.0.6 on 2024-09-17 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteDeclaracao', '0005_fotos_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryPageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('name1', models.CharField(max_length=100)),
                ('name2', models.CharField(max_length=100)),
                ('relationship_start_date', models.DateField()),
                ('relationship_start_time', models.TimeField()),
                ('message', models.TextField()),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='temporary_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('TemporaryPageData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_images', to='siteDeclaracao.temporarypagedata')),
            ],
        ),
    ]
