# Generated by Django 5.0.6 on 2024-09-19 02:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteDeclaracao', '0006_temporarypagedata_temporarypageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarypagedata',
            name='attempt_id',
            field=models.CharField(default=uuid.UUID('909c97f3-0b67-4984-b885-a53c8a491888'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='temporarypagedata',
            name='session_id',
            field=models.CharField(max_length=100),
        ),
    ]
