# Generated by Django 5.0.6 on 2024-09-20 04:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteDeclaracao', '0007_temporarypagedata_attempt_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('attempt_id', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('payment_status', models.CharField(max_length=100)),
                ('payment_status_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('active_time_month', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='temporarypagedata',
            name='attempt_id',
            field=models.CharField(default=uuid.UUID('f0c90925-d484-4d89-aa44-ed41e96513e1'), max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='PageRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_access', models.URLField(max_length=150, unique=True)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('nome1', models.CharField(max_length=100)),
                ('nome2', models.CharField(max_length=100)),
                ('relationship_start_date', models.DateField()),
                ('relationship_start_time', models.TimeField()),
                ('message', models.TextField()),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('DataUserPayment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_relationship', to='siteDeclaracao.datauserpayment')),
            ],
        ),
        migrations.CreateModel(
            name='PageRelationshipImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(default='image', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='relationship_files/')),
                ('PageRelationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_images', to='siteDeclaracao.pagerelationship')),
            ],
        ),
    ]
