# Generated by Django 5.0.6 on 2024-09-20 04:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteDeclaracao', '0008_datauserpayment_alter_temporarypagedata_attempt_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarypagedata',
            name='attempt_id',
            field=models.CharField(default=uuid.UUID('6a9982e3-31d4-4b8d-8d9e-5e3a41369824'), max_length=200, unique=True),
        ),
    ]
