# Generated by Django 5.0.6 on 2024-09-20 04:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteDeclaracao', '0009_alter_temporarypagedata_attempt_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagerelationship',
            old_name='nome1',
            new_name='name1',
        ),
        migrations.RenameField(
            model_name='pagerelationship',
            old_name='nome2',
            new_name='name2',
        ),
        migrations.AlterField(
            model_name='temporarypagedata',
            name='attempt_id',
            field=models.CharField(default=uuid.UUID('e745040f-5b76-4e6d-aeb2-b0e5c5a599db'), max_length=200, unique=True),
        ),
    ]
