# Generated by Django 5.0.6 on 2024-09-20 05:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteDeclaracao', '0010_rename_nome1_pagerelationship_name1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagerelationship',
            name='url_access_split',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='temporarypagedata',
            name='attempt_id',
            field=models.CharField(default=uuid.UUID('7208bb86-f174-4b6e-98ec-3eadde94f566'), max_length=200, unique=True),
        ),
    ]
