# Generated by Django 5.0.6 on 2024-09-20 15:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteDeclaracao', '0011_pagerelationship_url_access_split_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagerelationship',
            name='DataUserPayment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_user_Payment', to='siteDeclaracao.datauserpayment'),
        ),
        migrations.AlterField(
            model_name='temporarypagedata',
            name='attempt_id',
            field=models.CharField(default=uuid.UUID('50f55d36-a3b0-4aea-9ad1-655477c95a4d'), max_length=200, unique=True),
        ),
    ]
