# Generated by Django 5.0.6 on 2024-09-20 15:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteDeclaracao', '0012_alter_pagerelationship_datauserpayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarypagedata',
            name='attempt_id',
            field=models.CharField(default=uuid.UUID('9be3f9ad-8806-44e0-8b2b-ef70841b9c32'), max_length=200, unique=True),
        ),
    ]
