# Generated by Django 5.0.6 on 2024-06-25 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('porta', models.PositiveIntegerField()),
                ('numeracao_cto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CtoPrimaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numercao', models.IntegerField()),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descricao detalhada')),
                ('cor_fibra_entrada', models.CharField(max_length=20)),
                ('sinal_entrada', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Splitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('splitter_tipo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CtoSecundaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeracao', models.IntegerField()),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descricao detalhada')),
                ('sinal_entrada', models.FloatField()),
                ('clientes', models.ManyToManyField(blank=True, to='CTO_manager.cliente')),
                ('derivacao_ctoPrimaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CTO_manager.ctoprimaria')),
                ('splitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CTO_manager.splitter')),
            ],
        ),
        migrations.AddField(
            model_name='ctoprimaria',
            name='Splitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CTO_manager.splitter'),
        ),
    ]
