# Generated by Django 5.0.6 on 2024-06-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CTO_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='metragem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rg',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='status',
            field=models.CharField(default='ATIVO', max_length=15),
        ),
        migrations.AddField(
            model_name='ctosecundaria',
            name='metragem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numeracao_cto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='porta',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
