# Generated by Django 5.0.6 on 2024-06-28 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CTO_manager', '0002_cliente_metragem_cliente_rg_cliente_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctoprimaria',
            old_name='numercao',
            new_name='numeracao',
        ),
    ]
