# Generated by Django 5.0.6 on 2024-06-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CTO_manager', '0003_rename_numercao_ctoprimaria_numeracao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctoprimaria',
            old_name='Splitter',
            new_name='splitter',
        ),
    ]
