# Generated by Django 5.0.6 on 2024-07-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CTO_manager', '0004_rename_splitter_ctoprimaria_splitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctoprimaria',
            name='dio',
            field=models.TextField(blank=True, default='não identificado', null=True, verbose_name='Identificao DIO'),
        ),
        migrations.AddField(
            model_name='ctoprimaria',
            name='olt_porta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
