# Generated by Django 5.0.6 on 2024-08-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CTO_manager', '0005_ctoprimaria_dio_ctoprimaria_olt_porta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctoprimaria',
            name='conexoes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ctosecundaria',
            name='conexoes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
